production:
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 url: "postgres://mathavan:MAmyuRv2iFVLFUUKGvE2cBvUyM9tCnZH@dpg-chagdqrhp8u791jao1m0-a.oregon-postgres.render.com/mymovie"
development:
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 url: "postgres://mathavan:MAmyuRv2iFVLFUUKGvE2cBvUyM9tCnZH@dpg-chagdqrhp8u791jao1m0-a.oregon-postgres.render.com/mymovie"